INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Arroz', 2.5, 'kg', 'PENDING', 'HIGH');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Feijão', 1.5, 'kg', 'PURCHASED', 'MEDIUM');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Macarrão', 1.0, 'kg', 'PENDING', 'LOW');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Açúcar', 1.0, 'kg', 'PURCHASED', 'LOW');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Café', 0.5, 'kg', 'PENDING', 'MEDIUM');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Óleo de soja', 1.0, 'l', 'PENDING', 'HIGH');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Leite', 2.0, 'l', 'PENDING', 'MEDIUM');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Papel higiênico', 12.0, 'unidades', 'PENDING', 'LOW');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Sabão em pó', 1.0, 'kg', 'PENDING', 'MEDIUM');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Desinfetante', 1.0, 'l', 'PURCHASED', 'LOW');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Tomate', 1.0, 'kg', 'PENDING', 'MEDIUM');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Cebola', 1.0, 'kg', 'PENDING', 'LOW');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Alho', 0.2, 'kg', 'PENDING', 'HIGH');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Frango', 2.0, 'kg', 'PURCHASED', 'HIGH');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Carne bovina', 3.0, 'kg', 'PENDING', 'HIGH');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Cerveja', 6.0, 'l', 'PURCHASED', 'LOW');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Refrigerante', 2.0, 'l', 'PURCHASED', 'MEDIUM');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Água mineral', 10.0, 'l', 'PENDING', 'LOW');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Laranja', 1.0, 'kg', 'PENDING', 'MEDIUM');
INSERT INTO tb_item (name, quantity, unit, status, priority) VALUES ('Banana', 1.0, 'kg', 'PURCHASED', 'LOW');
